### ISSUE TITLE
Tag Package

### ISSUE THREAD

**Issue by sumityadav** [kodeine/laravel-meta#15]
Can you add a tag if the package is stable for use?

Thanks

**Comment by kodeine** [comment]
@sumityadav sure will do.
yes its stable

**Comment by ugurarici** [comment]
Tags would be great. Shows that it's a reliable package. I'm sure this way it also works but worry about future releases, for example you will update this package for Laravel 5.8 on "dev-master" but what if I want to go on with Laravel 5.5 ??

So, now I am afraid of add this useful package to my composer.json with "dev-master"

**Comment by sumityadav** [comment]
Since there is no movement on the project, I suggest utilizing https://github.com/spatie/laravel-schemaless-attributes.

**Comment by ugurarici** [comment]
Thanks @sumityadav 
I know about spatie/laravel-schemaless-attributes but it requires MySQL 5.7 or higher. 

We want to keep our projects to usable for most of the servers which comes with basic PHP, MySQL setup.
For example; we still keep some of our projects at Laravel 5.4 because Laravel requires PHP 7.* since 5.5 😕
