### ISSUE TITLE
Unable to add to Laravel 8

### ISSUE THREAD

**Issue by robeygo** [kodeine/laravel-meta#77]
Hi guys, 

Can this be added to a Laravel 8 app?

**Comment by JonathanMurre** [comment]
#78 is merged, but it does not have a new version yet, so composer won't pick it up. Hope this small think will be resolved quickly.

**Comment by siamak2** [comment]
@JonathanMurre 
I had the same problem when laravel 6 released: https://github.com/kodeine/laravel-meta/issues/65
my temporary solution was to add this to `composer.json` :
```
"repositories": [
	{
		"type": "vcs",
		"url": "https://github.com/kodeine/laravel-meta"
	}
]
```
then run `composer update kodeine/laravel-meta` and composer will now load the package from github instead of packagist.
once the new version of laravel-meta released remove it from `composer.json`

**Comment by kodeine** [comment]
siamak2, i've released the new version with those merges.
